### ISSUE TITLE
Arguments are not accessible within script files

### ISSUE THREAD

**Issue by franklinkim** [dreadl0ck/zeus#16]
Example:

if you have a layout like this:

```
zeus/
  scripts/
    foo.sh
```

and a command config like:

```yaml
commands:
 ...
 foo:
    arguments:
      - foo:String? = bar
...
```

you will not be able to access $foo:

```bash
# zeus/scripts/foo.sh
echo "${foo}"
```
