### ISSUE TITLE
Allow global variables in `outputs` definition

### ISSUE THREAD

**Issue by franklinkim** [dreadl0ck/zeus#17]
It would be great to dynamically define the output names depending on the global definitions.

Example:

```yaml
# commands.yml

globals:
  version: 1.0.0


commands:
  foo:
    outputs:
      - path/to/file-${version}
```
