### ISSUE TITLE
Allow globals as argument defaults

### ISSUE THREAD

**Issue by franklinkim** [dreadl0ck/zeus#18]
It would be great to use globals as default values for arguments:

```yaml
# commands.yml

globals:
  defaultVersion: 1.0.0

commands:
  install:
    arguments:
      - version:String? = ${defaultVersion}
```
