### ISSUE TITLE
Add `hidden` option on commands

### ISSUE THREAD

**Issue by franklinkim** [dreadl0ck/zeus#19]
It would be great to hide commands from the help e.g. for internal dependencies use

```yaml

commands:
  install:
    dependencies:
      - install-foo
    exec: echo "done"

  install-foo:
    hidden: true
    exec: ...
```
