### ISSUE TITLE
Allow arguments in outputs definition

### ISSUE THREAD

**Issue by franklinkim** [dreadl0ck/zeus#20]
It would be great to use the variables within the outputs definition as well, e.g.:

```yaml
...
  install:
    arguments:
      - version:String? = 0.1.0
    outputs:
      - path/to/file-${version}
...
```

Don't know if that is possible, depending on the order when it's been checked.
