### ISSUE TITLE
Option to change working directory on command

### ISSUE THREAD

**Issue by franklinkim** [dreadl0ck/zeus#21]
Would be great to define the working dir on the command instead of doing sth like `cd ... &&` in the exec:

```yaml
exampleCommand:
  cwd: ../
  exec: ls -la
```
