### ISSUE TITLE
How to use positional arguments or pass all args

### ISSUE THREAD

**Issue by khia** [dreadl0ck/zeus#8]
Is there any way to specify positional arguments? I am trying to reduce number of arguments I also wanted to have a nice help for the task. My command look like follow:
```
        search:
            description: Search through codebase
            help: search <grep arguments>
            exec: |
                  find `pwd` --name '*.erl' -print0 | xargs -0 grep $@
```

However I am getting:
```
» search foo
command search failed. error: invalid argument: foo
```

**Comment by dreadl0ck** [comment]
Hi there!

Labels are required for arguments,
because they are used as variable names in the script.

I would suggest the following:

```yaml
search:
            description: Search through codebase
            # search takes a keyword as argument, its a string and its not optional
            arguments:
              - keyword:String
            exec: |
                  # grep for keyword in project files
                  find `pwd` --name '*.erl' -print0 | xargs -0 grep $keyword
```

usage would then look like:

```
» search keyword=foo
```

This way you can further extend your search command in the future, add more search options etc

cheers
